#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <knit_counter_icons.h>

int32_t knit_counter_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm knit_counter!");

    return 0;
}
